// Copyright (C) 2020 The CodeActual Go Environment Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/core/v1 (interfaces: NamespacesGetter)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/client-go/kubernetes/typed/core/v1"
	reflect "reflect"
)

// MockNamespacesGetter is a mock of NamespacesGetter interface
type MockNamespacesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockNamespacesGetterMockRecorder
}

// MockNamespacesGetterMockRecorder is the mock recorder for MockNamespacesGetter
type MockNamespacesGetterMockRecorder struct {
	mock *MockNamespacesGetter
}

// NewMockNamespacesGetter creates a new mock instance
func NewMockNamespacesGetter(ctrl *gomock.Controller) *MockNamespacesGetter {
	mock := &MockNamespacesGetter{ctrl: ctrl}
	mock.recorder = &MockNamespacesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNamespacesGetter) EXPECT() *MockNamespacesGetterMockRecorder {
	return m.recorder
}

// Namespaces mocks base method
func (m *MockNamespacesGetter) Namespaces() v1.NamespaceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespaces")
	ret0, _ := ret[0].(v1.NamespaceInterface)
	return ret0
}

// Namespaces indicates an expected call of Namespaces
func (mr *MockNamespacesGetterMockRecorder) Namespaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespaces", reflect.TypeOf((*MockNamespacesGetter)(nil).Namespaces))
}
