// Copyright (C) 2020 The CodeActual Go Environment Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/rbac/v1 (interfaces: ClusterRoleBindingsGetter)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/client-go/kubernetes/typed/rbac/v1"
	reflect "reflect"
)

// MockClusterRoleBindingsGetter is a mock of ClusterRoleBindingsGetter interface
type MockClusterRoleBindingsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockClusterRoleBindingsGetterMockRecorder
}

// MockClusterRoleBindingsGetterMockRecorder is the mock recorder for MockClusterRoleBindingsGetter
type MockClusterRoleBindingsGetterMockRecorder struct {
	mock *MockClusterRoleBindingsGetter
}

// NewMockClusterRoleBindingsGetter creates a new mock instance
func NewMockClusterRoleBindingsGetter(ctrl *gomock.Controller) *MockClusterRoleBindingsGetter {
	mock := &MockClusterRoleBindingsGetter{ctrl: ctrl}
	mock.recorder = &MockClusterRoleBindingsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClusterRoleBindingsGetter) EXPECT() *MockClusterRoleBindingsGetterMockRecorder {
	return m.recorder
}

// ClusterRoleBindings mocks base method
func (m *MockClusterRoleBindingsGetter) ClusterRoleBindings() v1.ClusterRoleBindingInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterRoleBindings")
	ret0, _ := ret[0].(v1.ClusterRoleBindingInterface)
	return ret0
}

// ClusterRoleBindings indicates an expected call of ClusterRoleBindings
func (mr *MockClusterRoleBindingsGetterMockRecorder) ClusterRoleBindings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterRoleBindings", reflect.TypeOf((*MockClusterRoleBindingsGetter)(nil).ClusterRoleBindings))
}
